#!/bin/bash

log_file="/var/log/killusr.log"
echo "[ $(date) ] STARTED: killusr $1 $2" >> $log_file

# Fungsi penghapusan VMess
function delvm() {
    local user="$1"
    local exp=$(grep -w "^#vmg $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | head -n1)

    echo "[ $(date) ] Deleting VMess user: $user ($exp)" >> $log_file

    sed -i "/^#vm ${user} ${exp}/,/^},{/d" /etc/xray/config.json
    sed -i "/^#vmg ${user} ${exp}/,/^},{/d" /etc/xray/config.json
    rm -f /etc/vmess/akun/log-create-${user}.log
    rm -f /etc/vmess/${user}IP
    rm -f /etc/vmess/${user}
    rm -f /home/vps/public_html/vmess-${user}.txt
    systemctl restart xray
}

# Fungsi VLess
function delvl() {
    local user="$1"
    local exp=$(grep -w "^#vlg $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | head -n1)

    echo "[ $(date) ] Deleting VLess user: $user ($exp)" >> $log_file

    sed -i "/^#vl ${user} ${exp}/,/^},{/d" /etc/xray/config.json
    sed -i "/^#vlg ${user} ${exp}/,/^},{/d" /etc/xray/config.json
    rm -f /etc/vless/${user}IP
    rm -f /etc/vless/${user}
    rm -f /home/vps/public_html/vless-${user}.txt
    rm -f /etc/vless/akun/log-create-${user}.log
    systemctl restart xray
}

# Fungsi Trojan
function deltr() {
    local user="$1"
    local exp=$(grep -w "^#trg $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | head -n1)

    echo "[ $(date) ] Deleting Trojan user: $user ($exp)" >> $log_file

    sed -i "/^#tr ${user} ${exp}/,/^},{/d" /etc/xray/config.json
    sed -i "/^#trg ${user} ${exp}/,/^},{/d" /etc/xray/config.json
    rm -f /etc/trojan/${user}IP
    rm -f /etc/vless/${user}
    rm -f /home/vps/public_html/trojan-${user}.txt
    rm -f /etc/trojan/akun/log-create-${user}.log
    systemctl restart xray
}

# Fungsi Shadowsocks
function delss() {
    local user="$1"
    local exp=$(grep -w "^#!# $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | head -n1)

    echo "[ $(date) ] Deleting SS user: $user ($exp)" >> $log_file

    sed -i "/^#!# ${user} ${exp}/,/^},{/d" /etc/xray/config.json
    rm -f /etc/xray/limit/shadowsocks/quota/${user}
    rm -f /etc/xray/limit/shadowsocks/ip/${user}
    rm -f /etc/shadowsocks/${user}
    rm -f /etc/limit/shadowsocks/${user}
    rm -f /var/www/html/ss-${user}.txt
    sed -i "/^### ${user} ${exp}/d" /etc/.shadowsocks.db
    systemctl restart xray
}

# Fungsi SSH
function delssh() {
    local user="$1"

    echo "[ $(date) ] Deleting SSH user: $user" >> $log_file

    userdel -f ${user}
    rm -f /etc/xray/limit/ssh/ip/${user}
    rm -f /etc/julak/limit/ssh/ip/${user}
    rm -f /etc/ssh/${user}
    rm -f /var/www/html/ssh-${user}.txt
    sed -i "/^### ${user} /d" /etc/.ssh.db
    systemctl restart ws
    systemctl restart dropbear
}

# Fungsi NoobzVPNS
function delnoobz() {
    local user="$1"

    echo "[ $(date) ] Deleting Noobz user: $user" >> $log_file

    noobzvpns --remove-user ${user}
    sed -i "/^### $user/d" /etc/.noobz.db
    rm -f /var/www/html/noobzvpns-${user}.txt
    rm -f /etc/noobzvpns/${user}
    systemctl restart noobzvpns
}

# Eksekusi berdasarkan argumen
case "$1" in
  vm) delvm "$2" ;;
  vl) delvl "$2" ;;
  tr) deltr "$2" ;;
  ss) delss "$2" ;;
  ssh) delssh "$2" ;;
  nb) delnoobz "$2" ;;
  *)
    echo "[ $(date) ] Invalid or no action provided." >> $log_file
    ;;
esac
